/* soapStub.h
   Generated by gSOAP 2.8.23 from WebService.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"com.azwave.service.RibbonIntelPaperWsService"
#define SOAP_NAMESPACE_OF_ns2	"com.azurewave.domain.OperationResult"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20823
# error "GSOAP VERSION 20823 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__ribbonPaperCheck
#define SOAP_TYPE_ns1__ribbonPaperCheck (7)
/* ns1:ribbonPaperCheck */
class SOAP_CMAC ns1__ribbonPaperCheck
{
public:
	class ns1__ribbonPaperCheckRequest *ribbonPaperCheckRequest;	/* optional element of type ns1:ribbonPaperCheckRequest */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 7; } /* = unique type id SOAP_TYPE_ns1__ribbonPaperCheck */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ribbonPaperCheck() { ns1__ribbonPaperCheck::soap_default(NULL); }
	virtual ~ns1__ribbonPaperCheck() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ribbonPaperCheckRequest
#define SOAP_TYPE_ns1__ribbonPaperCheckRequest (8)
/* ns1:ribbonPaperCheckRequest */
class SOAP_CMAC ns1__ribbonPaperCheckRequest
{
public:
	char *hostName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique type id SOAP_TYPE_ns1__ribbonPaperCheckRequest */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ribbonPaperCheckRequest() { ns1__ribbonPaperCheckRequest::soap_default(NULL); }
	virtual ~ns1__ribbonPaperCheckRequest() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ribbonPaperCheckResponse
#define SOAP_TYPE_ns1__ribbonPaperCheckResponse (9)
/* ns1:ribbonPaperCheckResponse */
class SOAP_CMAC ns1__ribbonPaperCheckResponse
{
public:
	class ns2__OprationResult *ribbonPaperCheckResponse;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:OprationResult */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique type id SOAP_TYPE_ns1__ribbonPaperCheckResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ribbonPaperCheckResponse() { ns1__ribbonPaperCheckResponse::soap_default(NULL); }
	virtual ~ns1__ribbonPaperCheckResponse() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ribbonPaperIn
#define SOAP_TYPE_ns1__ribbonPaperIn (10)
/* ns1:ribbonPaperIn */
class SOAP_CMAC ns1__ribbonPaperIn
{
public:
	class ns1__ribbonIntelPaperRequest *ribbonPaperInRequest;	/* optional element of type ns1:ribbonIntelPaperRequest */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique type id SOAP_TYPE_ns1__ribbonPaperIn */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ribbonPaperIn() { ns1__ribbonPaperIn::soap_default(NULL); }
	virtual ~ns1__ribbonPaperIn() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ribbonIntelPaperRequest
#define SOAP_TYPE_ns1__ribbonIntelPaperRequest (11)
/* ns1:ribbonIntelPaperRequest */
class SOAP_CMAC ns1__ribbonIntelPaperRequest
{
public:
	char *hostname;	/* optional element of type xsd:string */
	char *labelPaper;	/* optional element of type xsd:string */
	char *ribbonNum;	/* optional element of type xsd:string */
	char *token;	/* optional element of type xsd:string */
	char *username;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique type id SOAP_TYPE_ns1__ribbonIntelPaperRequest */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ribbonIntelPaperRequest() { ns1__ribbonIntelPaperRequest::soap_default(NULL); }
	virtual ~ns1__ribbonIntelPaperRequest() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ribbonPaperInResponse
#define SOAP_TYPE_ns1__ribbonPaperInResponse (12)
/* ns1:ribbonPaperInResponse */
class SOAP_CMAC ns1__ribbonPaperInResponse
{
public:
	ns2__OprationResult *ribbonPaperInResponse;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:OprationResult */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique type id SOAP_TYPE_ns1__ribbonPaperInResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ribbonPaperInResponse() { ns1__ribbonPaperInResponse::soap_default(NULL); }
	virtual ~ns1__ribbonPaperInResponse() { }
};
#endif

#ifndef SOAP_TYPE_ns2__OprationResult
#define SOAP_TYPE_ns2__OprationResult (13)
/* ns2:OprationResult */
class SOAP_CMAC ns2__OprationResult
{
public:
	bool *result;	/* optional element of type xsd:boolean */
	char *error_USCOREtype;	/* required element of type xsd:string */
	int error_USCOREcode;	/* required element of type xsd:int */
	char *error_USCOREmessage;	/* required element of type xsd:string */
	char *debug_USCOREmessage;	/* required element of type xsd:string */
	LONG64 *totalExecuteTime;	/* optional element of type xsd:long */
	LONG64 *callProcExecuteTime;	/* optional element of type xsd:long */
	LONG64 *plsqlExecuteTime;	/* optional element of type xsd:long */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique type id SOAP_TYPE_ns2__OprationResult */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__OprationResult() { ns2__OprationResult::soap_default(NULL); }
	virtual ~ns2__OprationResult() { }
};
#endif

#ifndef SOAP_TYPE___ns1__ribbonPaperCheck
#define SOAP_TYPE___ns1__ribbonPaperCheck (25)
/* Operation wrapper: */
struct __ns1__ribbonPaperCheck
{
public:
	ns1__ribbonPaperCheck *ns1__ribbonPaperCheck_;	/* optional element of type ns1:ribbonPaperCheck */
public:
	int soap_type() const { return 25; } /* = unique type id SOAP_TYPE___ns1__ribbonPaperCheck */
};
#endif

#ifndef SOAP_TYPE___ns1__ribbonPaperIn
#define SOAP_TYPE___ns1__ribbonPaperIn (29)
/* Operation wrapper: */
struct __ns1__ribbonPaperIn
{
public:
	ns1__ribbonPaperIn *ns1__ribbonPaperIn_;	/* optional element of type ns1:ribbonPaperIn */
public:
	int soap_type() const { return 29; } /* = unique type id SOAP_TYPE___ns1__ribbonPaperIn */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (30)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 30; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (31)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 31; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (33)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 33; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (36)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 36; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (37)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 37; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
