/* soapRibbonIntelPaperWsServiceServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.23 from WebService.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapRibbonIntelPaperWsServiceServiceSoapBindingProxy_H
#define soapRibbonIntelPaperWsServiceServiceSoapBindingProxy_H
#include "soapH.h"

class SOAP_CMAC RibbonIntelPaperWsServiceServiceSoapBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'RibbonIntelPaperWsServiceServiceSoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in WebService.h (non-static)
	/// Constructor
	RibbonIntelPaperWsServiceServiceSoapBindingProxy();
	/// Construct from another engine state
	RibbonIntelPaperWsServiceServiceSoapBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	RibbonIntelPaperWsServiceServiceSoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	RibbonIntelPaperWsServiceServiceSoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	RibbonIntelPaperWsServiceServiceSoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	RibbonIntelPaperWsServiceServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor deletes deserialized data and engine context
	virtual	~RibbonIntelPaperWsServiceServiceSoapBindingProxy();
	/// Initializer used by constructors
	virtual	void RibbonIntelPaperWsServiceServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'ribbonPaperCheck' (returns error code or SOAP_OK)
	virtual	int ribbonPaperCheck(ns1__ribbonPaperCheck *ns1__ribbonPaperCheck_, ns1__ribbonPaperCheckResponse &ns1__ribbonPaperCheckResponse_) { return this->ribbonPaperCheck(NULL, NULL, ns1__ribbonPaperCheck_, ns1__ribbonPaperCheckResponse_); }
	virtual	int ribbonPaperCheck(const char *endpoint, const char *soap_action, ns1__ribbonPaperCheck *ns1__ribbonPaperCheck_, ns1__ribbonPaperCheckResponse &ns1__ribbonPaperCheckResponse_);

	/// Web service operation 'ribbonPaperIn' (returns error code or SOAP_OK)
	virtual	int ribbonPaperIn(ns1__ribbonPaperIn *ns1__ribbonPaperIn_, ns1__ribbonPaperInResponse &ns1__ribbonPaperInResponse_) { return this->ribbonPaperIn(NULL, NULL, ns1__ribbonPaperIn_, ns1__ribbonPaperInResponse_); }
	virtual	int ribbonPaperIn(const char *endpoint, const char *soap_action, ns1__ribbonPaperIn *ns1__ribbonPaperIn_, ns1__ribbonPaperInResponse &ns1__ribbonPaperInResponse_);
};
#endif
