/* soapH.h
   Generated by gSOAP 2.8.23 from WebService.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#ifndef soap_write_LONG64
#define soap_write_LONG64(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_LONG64(soap, data), 0) || soap_put_LONG64(soap, data, "long", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef soap_read_LONG64
#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);

#ifndef soap_write_bool
#define soap_write_bool(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_bool(soap, data), 0) || soap_put_bool(soap, data, "boolean", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);

#ifndef soap_read_bool
#define soap_read_bool(soap, data) ( soap_begin_recv(soap) || !soap_get_bool(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns2__OprationResult
#define SOAP_TYPE_ns2__OprationResult (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__OprationResult(struct soap*, const char*, int, const ns2__OprationResult *, const char*);
SOAP_FMAC3 ns2__OprationResult * SOAP_FMAC4 soap_in_ns2__OprationResult(struct soap*, const char*, ns2__OprationResult *, const char*);

#ifndef soap_write_ns2__OprationResult
#define soap_write_ns2__OprationResult(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:OprationResult", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns2__OprationResult * SOAP_FMAC4 soap_get_ns2__OprationResult(struct soap*, ns2__OprationResult *, const char*, const char*);

#ifndef soap_read_ns2__OprationResult
#define soap_read_ns2__OprationResult(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__OprationResult(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns2__OprationResult * SOAP_FMAC2 soap_instantiate_ns2__OprationResult(struct soap*, int, const char*, const char*, size_t*);

inline ns2__OprationResult * soap_new_ns2__OprationResult(struct soap *soap, int n = -1) { return soap_instantiate_ns2__OprationResult(soap, n, NULL, NULL, NULL); }

inline ns2__OprationResult * soap_new_req_ns2__OprationResult(struct soap *soap, char *error_USCOREtype, int error_USCOREcode, char *error_USCOREmessage, char *debug_USCOREmessage) { ns2__OprationResult *_p = soap_instantiate_ns2__OprationResult(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns2__OprationResult::error_USCOREtype = error_USCOREtype; _p->ns2__OprationResult::error_USCOREcode = error_USCOREcode; _p->ns2__OprationResult::error_USCOREmessage = error_USCOREmessage; _p->ns2__OprationResult::debug_USCOREmessage = debug_USCOREmessage; } return _p; }

inline ns2__OprationResult * soap_new_set_ns2__OprationResult(struct soap *soap, bool *result, char *error_USCOREtype, int error_USCOREcode, char *error_USCOREmessage, char *debug_USCOREmessage, LONG64 *totalExecuteTime, LONG64 *callProcExecuteTime, LONG64 *plsqlExecuteTime) { ns2__OprationResult *_p = soap_instantiate_ns2__OprationResult(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns2__OprationResult::result = result; _p->ns2__OprationResult::error_USCOREtype = error_USCOREtype; _p->ns2__OprationResult::error_USCOREcode = error_USCOREcode; _p->ns2__OprationResult::error_USCOREmessage = error_USCOREmessage; _p->ns2__OprationResult::debug_USCOREmessage = debug_USCOREmessage; _p->ns2__OprationResult::totalExecuteTime = totalExecuteTime; _p->ns2__OprationResult::callProcExecuteTime = callProcExecuteTime; _p->ns2__OprationResult::plsqlExecuteTime = plsqlExecuteTime; } return _p; }

inline void soap_delete_ns2__OprationResult(struct soap *soap, ns2__OprationResult *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__OprationResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ribbonPaperInResponse
#define SOAP_TYPE_ns1__ribbonPaperInResponse (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ribbonPaperInResponse(struct soap*, const char*, int, const ns1__ribbonPaperInResponse *, const char*);
SOAP_FMAC3 ns1__ribbonPaperInResponse * SOAP_FMAC4 soap_in_ns1__ribbonPaperInResponse(struct soap*, const char*, ns1__ribbonPaperInResponse *, const char*);

#ifndef soap_write_ns1__ribbonPaperInResponse
#define soap_write_ns1__ribbonPaperInResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ribbonPaperInResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonPaperInResponse * SOAP_FMAC4 soap_get_ns1__ribbonPaperInResponse(struct soap*, ns1__ribbonPaperInResponse *, const char*, const char*);

#ifndef soap_read_ns1__ribbonPaperInResponse
#define soap_read_ns1__ribbonPaperInResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ribbonPaperInResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__ribbonPaperInResponse * SOAP_FMAC2 soap_instantiate_ns1__ribbonPaperInResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__ribbonPaperInResponse * soap_new_ns1__ribbonPaperInResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__ribbonPaperInResponse(soap, n, NULL, NULL, NULL); }

inline ns1__ribbonPaperInResponse * soap_new_req_ns1__ribbonPaperInResponse(struct soap *soap) { ns1__ribbonPaperInResponse *_p = soap_instantiate_ns1__ribbonPaperInResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__ribbonPaperInResponse * soap_new_set_ns1__ribbonPaperInResponse(struct soap *soap, ns2__OprationResult *ribbonPaperInResponse) { ns1__ribbonPaperInResponse *_p = soap_instantiate_ns1__ribbonPaperInResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__ribbonPaperInResponse::ribbonPaperInResponse = ribbonPaperInResponse; } return _p; }

inline void soap_delete_ns1__ribbonPaperInResponse(struct soap *soap, ns1__ribbonPaperInResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ribbonPaperInResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ribbonIntelPaperRequest
#define SOAP_TYPE_ns1__ribbonIntelPaperRequest (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ribbonIntelPaperRequest(struct soap*, const char*, int, const ns1__ribbonIntelPaperRequest *, const char*);
SOAP_FMAC3 ns1__ribbonIntelPaperRequest * SOAP_FMAC4 soap_in_ns1__ribbonIntelPaperRequest(struct soap*, const char*, ns1__ribbonIntelPaperRequest *, const char*);

#ifndef soap_write_ns1__ribbonIntelPaperRequest
#define soap_write_ns1__ribbonIntelPaperRequest(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ribbonIntelPaperRequest", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonIntelPaperRequest * SOAP_FMAC4 soap_get_ns1__ribbonIntelPaperRequest(struct soap*, ns1__ribbonIntelPaperRequest *, const char*, const char*);

#ifndef soap_read_ns1__ribbonIntelPaperRequest
#define soap_read_ns1__ribbonIntelPaperRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ribbonIntelPaperRequest(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__ribbonIntelPaperRequest * SOAP_FMAC2 soap_instantiate_ns1__ribbonIntelPaperRequest(struct soap*, int, const char*, const char*, size_t*);

inline ns1__ribbonIntelPaperRequest * soap_new_ns1__ribbonIntelPaperRequest(struct soap *soap, int n = -1) { return soap_instantiate_ns1__ribbonIntelPaperRequest(soap, n, NULL, NULL, NULL); }

inline ns1__ribbonIntelPaperRequest * soap_new_req_ns1__ribbonIntelPaperRequest(struct soap *soap) { ns1__ribbonIntelPaperRequest *_p = soap_instantiate_ns1__ribbonIntelPaperRequest(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__ribbonIntelPaperRequest * soap_new_set_ns1__ribbonIntelPaperRequest(struct soap *soap, char *hostname, char *labelPaper, char *ribbonNum, char *token, char *username) { ns1__ribbonIntelPaperRequest *_p = soap_instantiate_ns1__ribbonIntelPaperRequest(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__ribbonIntelPaperRequest::hostname = hostname; _p->ns1__ribbonIntelPaperRequest::labelPaper = labelPaper; _p->ns1__ribbonIntelPaperRequest::ribbonNum = ribbonNum; _p->ns1__ribbonIntelPaperRequest::token = token; _p->ns1__ribbonIntelPaperRequest::username = username; } return _p; }

inline void soap_delete_ns1__ribbonIntelPaperRequest(struct soap *soap, ns1__ribbonIntelPaperRequest *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ribbonIntelPaperRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ribbonPaperIn
#define SOAP_TYPE_ns1__ribbonPaperIn (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ribbonPaperIn(struct soap*, const char*, int, const ns1__ribbonPaperIn *, const char*);
SOAP_FMAC3 ns1__ribbonPaperIn * SOAP_FMAC4 soap_in_ns1__ribbonPaperIn(struct soap*, const char*, ns1__ribbonPaperIn *, const char*);

#ifndef soap_write_ns1__ribbonPaperIn
#define soap_write_ns1__ribbonPaperIn(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ribbonPaperIn", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonPaperIn * SOAP_FMAC4 soap_get_ns1__ribbonPaperIn(struct soap*, ns1__ribbonPaperIn *, const char*, const char*);

#ifndef soap_read_ns1__ribbonPaperIn
#define soap_read_ns1__ribbonPaperIn(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ribbonPaperIn(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__ribbonPaperIn * SOAP_FMAC2 soap_instantiate_ns1__ribbonPaperIn(struct soap*, int, const char*, const char*, size_t*);

inline ns1__ribbonPaperIn * soap_new_ns1__ribbonPaperIn(struct soap *soap, int n = -1) { return soap_instantiate_ns1__ribbonPaperIn(soap, n, NULL, NULL, NULL); }

inline ns1__ribbonPaperIn * soap_new_req_ns1__ribbonPaperIn(struct soap *soap) { ns1__ribbonPaperIn *_p = soap_instantiate_ns1__ribbonPaperIn(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__ribbonPaperIn * soap_new_set_ns1__ribbonPaperIn(struct soap *soap, ns1__ribbonIntelPaperRequest *ribbonPaperInRequest) { ns1__ribbonPaperIn *_p = soap_instantiate_ns1__ribbonPaperIn(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__ribbonPaperIn::ribbonPaperInRequest = ribbonPaperInRequest; } return _p; }

inline void soap_delete_ns1__ribbonPaperIn(struct soap *soap, ns1__ribbonPaperIn *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ribbonPaperIn(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ribbonPaperCheckResponse
#define SOAP_TYPE_ns1__ribbonPaperCheckResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ribbonPaperCheckResponse(struct soap*, const char*, int, const ns1__ribbonPaperCheckResponse *, const char*);
SOAP_FMAC3 ns1__ribbonPaperCheckResponse * SOAP_FMAC4 soap_in_ns1__ribbonPaperCheckResponse(struct soap*, const char*, ns1__ribbonPaperCheckResponse *, const char*);

#ifndef soap_write_ns1__ribbonPaperCheckResponse
#define soap_write_ns1__ribbonPaperCheckResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ribbonPaperCheckResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonPaperCheckResponse * SOAP_FMAC4 soap_get_ns1__ribbonPaperCheckResponse(struct soap*, ns1__ribbonPaperCheckResponse *, const char*, const char*);

#ifndef soap_read_ns1__ribbonPaperCheckResponse
#define soap_read_ns1__ribbonPaperCheckResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ribbonPaperCheckResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__ribbonPaperCheckResponse * SOAP_FMAC2 soap_instantiate_ns1__ribbonPaperCheckResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__ribbonPaperCheckResponse * soap_new_ns1__ribbonPaperCheckResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__ribbonPaperCheckResponse(soap, n, NULL, NULL, NULL); }

inline ns1__ribbonPaperCheckResponse * soap_new_req_ns1__ribbonPaperCheckResponse(struct soap *soap) { ns1__ribbonPaperCheckResponse *_p = soap_instantiate_ns1__ribbonPaperCheckResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__ribbonPaperCheckResponse * soap_new_set_ns1__ribbonPaperCheckResponse(struct soap *soap, ns2__OprationResult *ribbonPaperCheckResponse) { ns1__ribbonPaperCheckResponse *_p = soap_instantiate_ns1__ribbonPaperCheckResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__ribbonPaperCheckResponse::ribbonPaperCheckResponse = ribbonPaperCheckResponse; } return _p; }

inline void soap_delete_ns1__ribbonPaperCheckResponse(struct soap *soap, ns1__ribbonPaperCheckResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ribbonPaperCheckResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ribbonPaperCheckRequest
#define SOAP_TYPE_ns1__ribbonPaperCheckRequest (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ribbonPaperCheckRequest(struct soap*, const char*, int, const ns1__ribbonPaperCheckRequest *, const char*);
SOAP_FMAC3 ns1__ribbonPaperCheckRequest * SOAP_FMAC4 soap_in_ns1__ribbonPaperCheckRequest(struct soap*, const char*, ns1__ribbonPaperCheckRequest *, const char*);

#ifndef soap_write_ns1__ribbonPaperCheckRequest
#define soap_write_ns1__ribbonPaperCheckRequest(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ribbonPaperCheckRequest", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonPaperCheckRequest * SOAP_FMAC4 soap_get_ns1__ribbonPaperCheckRequest(struct soap*, ns1__ribbonPaperCheckRequest *, const char*, const char*);

#ifndef soap_read_ns1__ribbonPaperCheckRequest
#define soap_read_ns1__ribbonPaperCheckRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ribbonPaperCheckRequest(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__ribbonPaperCheckRequest * SOAP_FMAC2 soap_instantiate_ns1__ribbonPaperCheckRequest(struct soap*, int, const char*, const char*, size_t*);

inline ns1__ribbonPaperCheckRequest * soap_new_ns1__ribbonPaperCheckRequest(struct soap *soap, int n = -1) { return soap_instantiate_ns1__ribbonPaperCheckRequest(soap, n, NULL, NULL, NULL); }

inline ns1__ribbonPaperCheckRequest * soap_new_req_ns1__ribbonPaperCheckRequest(struct soap *soap) { ns1__ribbonPaperCheckRequest *_p = soap_instantiate_ns1__ribbonPaperCheckRequest(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__ribbonPaperCheckRequest * soap_new_set_ns1__ribbonPaperCheckRequest(struct soap *soap, char *hostName) { ns1__ribbonPaperCheckRequest *_p = soap_instantiate_ns1__ribbonPaperCheckRequest(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__ribbonPaperCheckRequest::hostName = hostName; } return _p; }

inline void soap_delete_ns1__ribbonPaperCheckRequest(struct soap *soap, ns1__ribbonPaperCheckRequest *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ribbonPaperCheckRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ribbonPaperCheck
#define SOAP_TYPE_ns1__ribbonPaperCheck (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ribbonPaperCheck(struct soap*, const char*, int, const ns1__ribbonPaperCheck *, const char*);
SOAP_FMAC3 ns1__ribbonPaperCheck * SOAP_FMAC4 soap_in_ns1__ribbonPaperCheck(struct soap*, const char*, ns1__ribbonPaperCheck *, const char*);

#ifndef soap_write_ns1__ribbonPaperCheck
#define soap_write_ns1__ribbonPaperCheck(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ribbonPaperCheck", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonPaperCheck * SOAP_FMAC4 soap_get_ns1__ribbonPaperCheck(struct soap*, ns1__ribbonPaperCheck *, const char*, const char*);

#ifndef soap_read_ns1__ribbonPaperCheck
#define soap_read_ns1__ribbonPaperCheck(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ribbonPaperCheck(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__ribbonPaperCheck * SOAP_FMAC2 soap_instantiate_ns1__ribbonPaperCheck(struct soap*, int, const char*, const char*, size_t*);

inline ns1__ribbonPaperCheck * soap_new_ns1__ribbonPaperCheck(struct soap *soap, int n = -1) { return soap_instantiate_ns1__ribbonPaperCheck(soap, n, NULL, NULL, NULL); }

inline ns1__ribbonPaperCheck * soap_new_req_ns1__ribbonPaperCheck(struct soap *soap) { ns1__ribbonPaperCheck *_p = soap_instantiate_ns1__ribbonPaperCheck(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__ribbonPaperCheck * soap_new_set_ns1__ribbonPaperCheck(struct soap *soap, ns1__ribbonPaperCheckRequest *ribbonPaperCheckRequest) { ns1__ribbonPaperCheck *_p = soap_instantiate_ns1__ribbonPaperCheck(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__ribbonPaperCheck::ribbonPaperCheckRequest = ribbonPaperCheckRequest; } return _p; }

inline void soap_delete_ns1__ribbonPaperCheck(struct soap *soap, ns1__ribbonPaperCheck *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ribbonPaperCheck(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__ribbonPaperIn
#define SOAP_TYPE___ns1__ribbonPaperIn (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__ribbonPaperIn(struct soap*, struct __ns1__ribbonPaperIn *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__ribbonPaperIn(struct soap*, const struct __ns1__ribbonPaperIn *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__ribbonPaperIn(struct soap*, const char*, int, const struct __ns1__ribbonPaperIn *, const char*);
SOAP_FMAC3 struct __ns1__ribbonPaperIn * SOAP_FMAC4 soap_in___ns1__ribbonPaperIn(struct soap*, const char*, struct __ns1__ribbonPaperIn *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__ribbonPaperIn(struct soap*, const struct __ns1__ribbonPaperIn *, const char*, const char*);

#ifndef soap_write___ns1__ribbonPaperIn
#define soap_write___ns1__ribbonPaperIn(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__ribbonPaperIn(soap, data), 0) || soap_put___ns1__ribbonPaperIn(soap, data, "-ns1:ribbonPaperIn", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__ribbonPaperIn * SOAP_FMAC4 soap_get___ns1__ribbonPaperIn(struct soap*, struct __ns1__ribbonPaperIn *, const char*, const char*);

#ifndef soap_read___ns1__ribbonPaperIn
#define soap_read___ns1__ribbonPaperIn(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__ribbonPaperIn(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__ribbonPaperIn * SOAP_FMAC2 soap_instantiate___ns1__ribbonPaperIn(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__ribbonPaperIn * soap_new___ns1__ribbonPaperIn(struct soap *soap, int n = -1) { return soap_instantiate___ns1__ribbonPaperIn(soap, n, NULL, NULL, NULL); }

inline struct __ns1__ribbonPaperIn * soap_new_req___ns1__ribbonPaperIn(struct soap *soap) { struct __ns1__ribbonPaperIn *_p = soap_instantiate___ns1__ribbonPaperIn(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__ribbonPaperIn(soap, _p); } return _p; }

inline struct __ns1__ribbonPaperIn * soap_new_set___ns1__ribbonPaperIn(struct soap *soap, ns1__ribbonPaperIn *ns1__ribbonPaperIn_) { struct __ns1__ribbonPaperIn *_p = soap_instantiate___ns1__ribbonPaperIn(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__ribbonPaperIn(soap, _p); _p->ns1__ribbonPaperIn_ = ns1__ribbonPaperIn_; } return _p; }

inline void soap_delete___ns1__ribbonPaperIn(struct soap *soap, struct __ns1__ribbonPaperIn *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__ribbonPaperIn(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__ribbonPaperCheck
#define SOAP_TYPE___ns1__ribbonPaperCheck (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__ribbonPaperCheck(struct soap*, struct __ns1__ribbonPaperCheck *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__ribbonPaperCheck(struct soap*, const struct __ns1__ribbonPaperCheck *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__ribbonPaperCheck(struct soap*, const char*, int, const struct __ns1__ribbonPaperCheck *, const char*);
SOAP_FMAC3 struct __ns1__ribbonPaperCheck * SOAP_FMAC4 soap_in___ns1__ribbonPaperCheck(struct soap*, const char*, struct __ns1__ribbonPaperCheck *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__ribbonPaperCheck(struct soap*, const struct __ns1__ribbonPaperCheck *, const char*, const char*);

#ifndef soap_write___ns1__ribbonPaperCheck
#define soap_write___ns1__ribbonPaperCheck(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__ribbonPaperCheck(soap, data), 0) || soap_put___ns1__ribbonPaperCheck(soap, data, "-ns1:ribbonPaperCheck", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__ribbonPaperCheck * SOAP_FMAC4 soap_get___ns1__ribbonPaperCheck(struct soap*, struct __ns1__ribbonPaperCheck *, const char*, const char*);

#ifndef soap_read___ns1__ribbonPaperCheck
#define soap_read___ns1__ribbonPaperCheck(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__ribbonPaperCheck(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__ribbonPaperCheck * SOAP_FMAC2 soap_instantiate___ns1__ribbonPaperCheck(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__ribbonPaperCheck * soap_new___ns1__ribbonPaperCheck(struct soap *soap, int n = -1) { return soap_instantiate___ns1__ribbonPaperCheck(soap, n, NULL, NULL, NULL); }

inline struct __ns1__ribbonPaperCheck * soap_new_req___ns1__ribbonPaperCheck(struct soap *soap) { struct __ns1__ribbonPaperCheck *_p = soap_instantiate___ns1__ribbonPaperCheck(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__ribbonPaperCheck(soap, _p); } return _p; }

inline struct __ns1__ribbonPaperCheck * soap_new_set___ns1__ribbonPaperCheck(struct soap *soap, ns1__ribbonPaperCheck *ns1__ribbonPaperCheck_) { struct __ns1__ribbonPaperCheck *_p = soap_instantiate___ns1__ribbonPaperCheck(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__ribbonPaperCheck(soap, _p); _p->ns1__ribbonPaperCheck_ = ns1__ribbonPaperCheck_; } return _p; }

inline void soap_delete___ns1__ribbonPaperCheck(struct soap *soap, struct __ns1__ribbonPaperCheck *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__ribbonPaperCheck(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons1__ribbonPaperIn
#define SOAP_TYPE_PointerTons1__ribbonPaperIn (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ribbonPaperIn(struct soap*, ns1__ribbonPaperIn *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ribbonPaperIn(struct soap*, const char *, int, ns1__ribbonPaperIn *const*, const char *);
SOAP_FMAC3 ns1__ribbonPaperIn ** SOAP_FMAC4 soap_in_PointerTons1__ribbonPaperIn(struct soap*, const char*, ns1__ribbonPaperIn **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ribbonPaperIn(struct soap*, ns1__ribbonPaperIn *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__ribbonPaperIn
#define soap_write_PointerTons1__ribbonPaperIn(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__ribbonPaperIn(soap, data), 0) || soap_put_PointerTons1__ribbonPaperIn(soap, data, "ns1:ribbonPaperIn", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonPaperIn ** SOAP_FMAC4 soap_get_PointerTons1__ribbonPaperIn(struct soap*, ns1__ribbonPaperIn **, const char*, const char*);

#ifndef soap_read_PointerTons1__ribbonPaperIn
#define soap_read_PointerTons1__ribbonPaperIn(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ribbonPaperIn(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__ribbonPaperCheck
#define SOAP_TYPE_PointerTons1__ribbonPaperCheck (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ribbonPaperCheck(struct soap*, ns1__ribbonPaperCheck *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ribbonPaperCheck(struct soap*, const char *, int, ns1__ribbonPaperCheck *const*, const char *);
SOAP_FMAC3 ns1__ribbonPaperCheck ** SOAP_FMAC4 soap_in_PointerTons1__ribbonPaperCheck(struct soap*, const char*, ns1__ribbonPaperCheck **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ribbonPaperCheck(struct soap*, ns1__ribbonPaperCheck *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__ribbonPaperCheck
#define soap_write_PointerTons1__ribbonPaperCheck(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__ribbonPaperCheck(soap, data), 0) || soap_put_PointerTons1__ribbonPaperCheck(soap, data, "ns1:ribbonPaperCheck", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonPaperCheck ** SOAP_FMAC4 soap_get_PointerTons1__ribbonPaperCheck(struct soap*, ns1__ribbonPaperCheck **, const char*, const char*);

#ifndef soap_read_PointerTons1__ribbonPaperCheck
#define soap_read_PointerTons1__ribbonPaperCheck(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ribbonPaperCheck(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToLONG64
#define SOAP_TYPE_PointerToLONG64 (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToLONG64(struct soap*, LONG64 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToLONG64(struct soap*, const char *, int, LONG64 *const*, const char *);
SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_in_PointerToLONG64(struct soap*, const char*, LONG64 **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToLONG64(struct soap*, LONG64 *const*, const char*, const char*);

#ifndef soap_write_PointerToLONG64
#define soap_write_PointerToLONG64(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToLONG64(soap, data), 0) || soap_put_PointerToLONG64(soap, data, "long", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_get_PointerToLONG64(struct soap*, LONG64 **, const char*, const char*);

#ifndef soap_read_PointerToLONG64
#define soap_read_PointerToLONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToLONG64(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTobool
#define SOAP_TYPE_PointerTobool (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTobool(struct soap*, bool *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTobool(struct soap*, const char *, int, bool *const*, const char *);
SOAP_FMAC3 bool ** SOAP_FMAC4 soap_in_PointerTobool(struct soap*, const char*, bool **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTobool(struct soap*, bool *const*, const char*, const char*);

#ifndef soap_write_PointerTobool
#define soap_write_PointerTobool(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTobool(soap, data), 0) || soap_put_PointerTobool(soap, data, "boolean", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 bool ** SOAP_FMAC4 soap_get_PointerTobool(struct soap*, bool **, const char*, const char*);

#ifndef soap_read_PointerTobool
#define soap_read_PointerTobool(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTobool(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__ribbonIntelPaperRequest
#define SOAP_TYPE_PointerTons1__ribbonIntelPaperRequest (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ribbonIntelPaperRequest(struct soap*, ns1__ribbonIntelPaperRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ribbonIntelPaperRequest(struct soap*, const char *, int, ns1__ribbonIntelPaperRequest *const*, const char *);
SOAP_FMAC3 ns1__ribbonIntelPaperRequest ** SOAP_FMAC4 soap_in_PointerTons1__ribbonIntelPaperRequest(struct soap*, const char*, ns1__ribbonIntelPaperRequest **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ribbonIntelPaperRequest(struct soap*, ns1__ribbonIntelPaperRequest *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__ribbonIntelPaperRequest
#define soap_write_PointerTons1__ribbonIntelPaperRequest(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__ribbonIntelPaperRequest(soap, data), 0) || soap_put_PointerTons1__ribbonIntelPaperRequest(soap, data, "ns1:ribbonIntelPaperRequest", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonIntelPaperRequest ** SOAP_FMAC4 soap_get_PointerTons1__ribbonIntelPaperRequest(struct soap*, ns1__ribbonIntelPaperRequest **, const char*, const char*);

#ifndef soap_read_PointerTons1__ribbonIntelPaperRequest
#define soap_read_PointerTons1__ribbonIntelPaperRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ribbonIntelPaperRequest(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__OprationResult
#define SOAP_TYPE_PointerTons2__OprationResult (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__OprationResult(struct soap*, ns2__OprationResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__OprationResult(struct soap*, const char *, int, ns2__OprationResult *const*, const char *);
SOAP_FMAC3 ns2__OprationResult ** SOAP_FMAC4 soap_in_PointerTons2__OprationResult(struct soap*, const char*, ns2__OprationResult **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__OprationResult(struct soap*, ns2__OprationResult *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__OprationResult
#define soap_write_PointerTons2__OprationResult(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons2__OprationResult(soap, data), 0) || soap_put_PointerTons2__OprationResult(soap, data, "ns2:OprationResult", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns2__OprationResult ** SOAP_FMAC4 soap_get_PointerTons2__OprationResult(struct soap*, ns2__OprationResult **, const char*, const char*);

#ifndef soap_read_PointerTons2__OprationResult
#define soap_read_PointerTons2__OprationResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__OprationResult(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__ribbonPaperCheckRequest
#define SOAP_TYPE_PointerTons1__ribbonPaperCheckRequest (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ribbonPaperCheckRequest(struct soap*, ns1__ribbonPaperCheckRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ribbonPaperCheckRequest(struct soap*, const char *, int, ns1__ribbonPaperCheckRequest *const*, const char *);
SOAP_FMAC3 ns1__ribbonPaperCheckRequest ** SOAP_FMAC4 soap_in_PointerTons1__ribbonPaperCheckRequest(struct soap*, const char*, ns1__ribbonPaperCheckRequest **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ribbonPaperCheckRequest(struct soap*, ns1__ribbonPaperCheckRequest *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__ribbonPaperCheckRequest
#define soap_write_PointerTons1__ribbonPaperCheckRequest(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__ribbonPaperCheckRequest(soap, data), 0) || soap_put_PointerTons1__ribbonPaperCheckRequest(soap, data, "ns1:ribbonPaperCheckRequest", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__ribbonPaperCheckRequest ** SOAP_FMAC4 soap_get_PointerTons1__ribbonPaperCheckRequest(struct soap*, ns1__ribbonPaperCheckRequest **, const char*, const char*);

#ifndef soap_read_PointerTons1__ribbonPaperCheckRequest
#define soap_read_PointerTons1__ribbonPaperCheckRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ribbonPaperCheckRequest(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of soapH.h */
