/* soapRibbonIntelPaperWsServiceServiceSoapBindingProxy.cpp
   Generated by gSOAP 2.8.23 from WebService.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapRibbonIntelPaperWsServiceServiceSoapBindingProxy.h"

RibbonIntelPaperWsServiceServiceSoapBindingProxy::RibbonIntelPaperWsServiceServiceSoapBindingProxy() : soap(SOAP_IO_DEFAULT)
{	RibbonIntelPaperWsServiceServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

RibbonIntelPaperWsServiceServiceSoapBindingProxy::RibbonIntelPaperWsServiceServiceSoapBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

RibbonIntelPaperWsServiceServiceSoapBindingProxy::RibbonIntelPaperWsServiceServiceSoapBindingProxy(const char *url) : soap(SOAP_IO_DEFAULT)
{	RibbonIntelPaperWsServiceServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

RibbonIntelPaperWsServiceServiceSoapBindingProxy::RibbonIntelPaperWsServiceServiceSoapBindingProxy(soap_mode iomode) : soap(iomode)
{	RibbonIntelPaperWsServiceServiceSoapBindingProxy_init(iomode, iomode);
}

RibbonIntelPaperWsServiceServiceSoapBindingProxy::RibbonIntelPaperWsServiceServiceSoapBindingProxy(const char *url, soap_mode iomode) : soap(iomode)
{	RibbonIntelPaperWsServiceServiceSoapBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

RibbonIntelPaperWsServiceServiceSoapBindingProxy::RibbonIntelPaperWsServiceServiceSoapBindingProxy(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	RibbonIntelPaperWsServiceServiceSoapBindingProxy_init(imode, omode);
}

RibbonIntelPaperWsServiceServiceSoapBindingProxy::~RibbonIntelPaperWsServiceServiceSoapBindingProxy()
{
	this->destroy();
	}

void RibbonIntelPaperWsServiceServiceSoapBindingProxy::RibbonIntelPaperWsServiceServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "com.azurewave.domain.OperationResult", NULL, NULL},
	{"ns1", "com.azwave.service.RibbonIntelPaperWsService", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void RibbonIntelPaperWsServiceServiceSoapBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void RibbonIntelPaperWsServiceServiceSoapBindingProxy::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	RibbonIntelPaperWsServiceServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_fault()
{	return this->fault;
}

const char *RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *RibbonIntelPaperWsServiceServiceSoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int RibbonIntelPaperWsServiceServiceSoapBindingProxy::ribbonPaperCheck(const char *endpoint, const char *soap_action, ns1__ribbonPaperCheck *ns1__ribbonPaperCheck_, ns1__ribbonPaperCheckResponse &ns1__ribbonPaperCheckResponse_)
{	struct soap *soap = this;
	struct __ns1__ribbonPaperCheck soap_tmp___ns1__ribbonPaperCheck;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.216.158:8083/ribbonIntelWs";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ribbonPaperCheck.ns1__ribbonPaperCheck_ = ns1__ribbonPaperCheck_;
	soap_serializeheader(soap);
	soap_serialize___ns1__ribbonPaperCheck(soap, &soap_tmp___ns1__ribbonPaperCheck);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ribbonPaperCheck(soap, &soap_tmp___ns1__ribbonPaperCheck, "-ns1:ribbonPaperCheck", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ribbonPaperCheck(soap, &soap_tmp___ns1__ribbonPaperCheck, "-ns1:ribbonPaperCheck", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ribbonPaperCheckResponse_)
		return soap_closesock(soap);
	ns1__ribbonPaperCheckResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ribbonPaperCheckResponse_.soap_get(soap, "ns1:ribbonPaperCheckResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int RibbonIntelPaperWsServiceServiceSoapBindingProxy::ribbonPaperIn(const char *endpoint, const char *soap_action, ns1__ribbonPaperIn *ns1__ribbonPaperIn_, ns1__ribbonPaperInResponse &ns1__ribbonPaperInResponse_)
{	struct soap *soap = this;
	struct __ns1__ribbonPaperIn soap_tmp___ns1__ribbonPaperIn;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.216.158:8083/ribbonIntelWs";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ribbonPaperIn.ns1__ribbonPaperIn_ = ns1__ribbonPaperIn_;
	soap_serializeheader(soap);
	soap_serialize___ns1__ribbonPaperIn(soap, &soap_tmp___ns1__ribbonPaperIn);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ribbonPaperIn(soap, &soap_tmp___ns1__ribbonPaperIn, "-ns1:ribbonPaperIn", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ribbonPaperIn(soap, &soap_tmp___ns1__ribbonPaperIn, "-ns1:ribbonPaperIn", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ribbonPaperInResponse_)
		return soap_closesock(soap);
	ns1__ribbonPaperInResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ribbonPaperInResponse_.soap_get(soap, "ns1:ribbonPaperInResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
