/* WebService.h
   Generated by wsdl2h 2.8.23 from http://192.168.216.158:8083/ribbonIntelWs?wsdl and typemap.dat
   2025-11-17 06:49:34 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2015 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on WebService.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   com.azwave.service.RibbonIntelPaperWsService                             *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "com.azwave.service.RibbonIntelPaperWsService"
ns2 = "com.azurewave.domain.OperationResult"

*/

#define SOAP_NAMESPACE_OF_ns1	"com.azwave.service.RibbonIntelPaperWsService"
//gsoap ns1   schema namespace:	com.azwave.service.RibbonIntelPaperWsService
//gsoap ns1   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns2	"com.azurewave.domain.OperationResult"
//gsoap ns2   schema namespace:	com.azurewave.domain.OperationResult
//gsoap ns2   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class ns1__ribbonPaperCheck.
class ns1__ribbonPaperCheck;

//  Forward declaration of class ns1__ribbonPaperCheckRequest.
class ns1__ribbonPaperCheckRequest;

//  Forward declaration of class ns1__ribbonPaperCheckResponse.
class ns1__ribbonPaperCheckResponse;

//  Forward declaration of class ns1__ribbonPaperIn.
class ns1__ribbonPaperIn;

//  Forward declaration of class ns1__ribbonIntelPaperRequest.
class ns1__ribbonIntelPaperRequest;

//  Forward declaration of class ns1__ribbonPaperInResponse.
class ns1__ribbonPaperInResponse;

//  Forward declaration of class ns2__OprationResult.
class ns2__OprationResult;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   com.azwave.service.RibbonIntelPaperWsService                             *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   com.azurewave.domain.OperationResult                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   com.azwave.service.RibbonIntelPaperWsService                             *
 *                                                                            *
\******************************************************************************/

/// @brief "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperCheck is a complexType.
///
/// class ns1__ribbonPaperCheck operations:
/// - soap_new_ns1__ribbonPaperCheck(soap*) allocate
/// - soap_new_ns1__ribbonPaperCheck(soap*, int num) allocate array
/// - soap_new_req_ns1__ribbonPaperCheck(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ribbonPaperCheck(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ribbonPaperCheck(soap*, ns1__ribbonPaperCheck*) deserialize from a stream
/// - int soap_write_ns1__ribbonPaperCheck(soap, ns1__ribbonPaperCheck*) serialize to a stream
class ns1__ribbonPaperCheck
{ public:
/// Element "ribbonPaperCheckRequest" of XSD type "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperCheckRequest.
    ns1__ribbonPaperCheckRequest*        ribbonPaperCheckRequest        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperCheckRequest is a complexType.
///
/// class ns1__ribbonPaperCheckRequest operations:
/// - soap_new_ns1__ribbonPaperCheckRequest(soap*) allocate
/// - soap_new_ns1__ribbonPaperCheckRequest(soap*, int num) allocate array
/// - soap_new_req_ns1__ribbonPaperCheckRequest(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ribbonPaperCheckRequest(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ribbonPaperCheckRequest(soap*, ns1__ribbonPaperCheckRequest*) deserialize from a stream
/// - int soap_write_ns1__ribbonPaperCheckRequest(soap, ns1__ribbonPaperCheckRequest*) serialize to a stream
class ns1__ribbonPaperCheckRequest
{ public:
/// Element "hostName" of XSD type xs:string.
    char*                                hostName                       0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperCheckResponse is a complexType.
///
/// class ns1__ribbonPaperCheckResponse operations:
/// - soap_new_ns1__ribbonPaperCheckResponse(soap*) allocate
/// - soap_new_ns1__ribbonPaperCheckResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__ribbonPaperCheckResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ribbonPaperCheckResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ribbonPaperCheckResponse(soap*, ns1__ribbonPaperCheckResponse*) deserialize from a stream
/// - int soap_write_ns1__ribbonPaperCheckResponse(soap, ns1__ribbonPaperCheckResponse*) serialize to a stream
class ns1__ribbonPaperCheckResponse
{ public:
/// Element "ribbonPaperCheckResponse" of XSD type "com.azurewave.domain.OperationResult":OprationResult.
    ns2__OprationResult*                 ribbonPaperCheckResponse       0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperIn is a complexType.
///
/// class ns1__ribbonPaperIn operations:
/// - soap_new_ns1__ribbonPaperIn(soap*) allocate
/// - soap_new_ns1__ribbonPaperIn(soap*, int num) allocate array
/// - soap_new_req_ns1__ribbonPaperIn(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ribbonPaperIn(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ribbonPaperIn(soap*, ns1__ribbonPaperIn*) deserialize from a stream
/// - int soap_write_ns1__ribbonPaperIn(soap, ns1__ribbonPaperIn*) serialize to a stream
class ns1__ribbonPaperIn
{ public:
/// Element "ribbonPaperInRequest" of XSD type "com.azwave.service.RibbonIntelPaperWsService":ribbonIntelPaperRequest.
    ns1__ribbonIntelPaperRequest*        ribbonPaperInRequest           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "com.azwave.service.RibbonIntelPaperWsService":ribbonIntelPaperRequest is a complexType.
///
/// class ns1__ribbonIntelPaperRequest operations:
/// - soap_new_ns1__ribbonIntelPaperRequest(soap*) allocate
/// - soap_new_ns1__ribbonIntelPaperRequest(soap*, int num) allocate array
/// - soap_new_req_ns1__ribbonIntelPaperRequest(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ribbonIntelPaperRequest(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ribbonIntelPaperRequest(soap*, ns1__ribbonIntelPaperRequest*) deserialize from a stream
/// - int soap_write_ns1__ribbonIntelPaperRequest(soap, ns1__ribbonIntelPaperRequest*) serialize to a stream
class ns1__ribbonIntelPaperRequest
{ public:
/// Element "hostname" of XSD type xs:string.
    char*                                hostname                       0;	///< Optional element.
/// Element "labelPaper" of XSD type xs:string.
    char*                                labelPaper                     0;	///< Optional element.
/// Element "ribbonNum" of XSD type xs:string.
    char*                                ribbonNum                      0;	///< Optional element.
/// Element "token" of XSD type xs:string.
    char*                                token                          0;	///< Optional element.
/// Element "username" of XSD type xs:string.
    char*                                username                       0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperInResponse is a complexType.
///
/// class ns1__ribbonPaperInResponse operations:
/// - soap_new_ns1__ribbonPaperInResponse(soap*) allocate
/// - soap_new_ns1__ribbonPaperInResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__ribbonPaperInResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ribbonPaperInResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ribbonPaperInResponse(soap*, ns1__ribbonPaperInResponse*) deserialize from a stream
/// - int soap_write_ns1__ribbonPaperInResponse(soap, ns1__ribbonPaperInResponse*) serialize to a stream
class ns1__ribbonPaperInResponse
{ public:
/// Element "ribbonPaperInResponse" of XSD type "com.azurewave.domain.OperationResult":OprationResult.
    ns2__OprationResult*                 ribbonPaperInResponse          0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   com.azurewave.domain.OperationResult                                     *
 *                                                                            *
\******************************************************************************/

/// @brief "com.azurewave.domain.OperationResult":OprationResult is a complexType.
///
/// class ns2__OprationResult operations:
/// - soap_new_ns2__OprationResult(soap*) allocate
/// - soap_new_ns2__OprationResult(soap*, int num) allocate array
/// - soap_new_req_ns2__OprationResult(soap*, ...) allocate, set required members
/// - soap_new_set_ns2__OprationResult(soap*, ...) allocate, set all public members
/// - int soap_read_ns2__OprationResult(soap*, ns2__OprationResult*) deserialize from a stream
/// - int soap_write_ns2__OprationResult(soap, ns2__OprationResult*) serialize to a stream
class ns2__OprationResult
{ public:
/// Element "result" of XSD type xs:boolean.
    bool*                                result                        ;	///< Nillable pointer.
/// Element "error_type" of XSD type xs:string.
    char*                                error_USCOREtype               1;	///< Required element.
/// Element "error_code" of XSD type xs:int.
    int                                  error_USCOREcode               1;	///< Required element.
/// Element "error_message" of XSD type xs:string.
    char*                                error_USCOREmessage            1;	///< Required element.
/// Element "debug_message" of XSD type xs:string.
    char*                                debug_USCOREmessage            1;	///< Required element.
/// Element "totalExecuteTime" of XSD type xs:long.
    LONG64*                              totalExecuteTime              ;	///< Nillable pointer.
/// Element "callProcExecuteTime" of XSD type xs:long.
    LONG64*                              callProcExecuteTime           ;	///< Nillable pointer.
/// Element "plsqlExecuteTime" of XSD type xs:long.
    LONG64*                              plsqlExecuteTime              ;	///< Nillable pointer.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   com.azwave.service.RibbonIntelPaperWsService                             *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperCheck of XSD type "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperCheck.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// @brief Top-level root element "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperCheckResponse of XSD type "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperCheckResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// @brief Top-level root element "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperIn of XSD type "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperIn.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// @brief Top-level root element "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperInResponse of XSD type "com.azwave.service.RibbonIntelPaperWsService":ribbonPaperInResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   com.azwave.service.RibbonIntelPaperWsService                             *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   com.azurewave.domain.OperationResult                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   com.azurewave.domain.OperationResult                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	RibbonIntelPaperWsServiceServiceSoapBinding 
//gsoap ns1  service type:	RibbonIntelPaperWsService 
//gsoap ns1  service port:	http://192.168.216.158:8083/ribbonIntelWs 
//gsoap ns1  service namespace:	com.azwave.service.RibbonIntelPaperWsService 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage RibbonIntelPaperWsServiceService Definitions

@section RibbonIntelPaperWsServiceService_bindings Service Bindings

  - @ref RibbonIntelPaperWsServiceServiceSoapBinding

@section RibbonIntelPaperWsServiceService_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page RibbonIntelPaperWsServiceServiceSoapBinding Binding "RibbonIntelPaperWsServiceServiceSoapBinding"

@section RibbonIntelPaperWsServiceServiceSoapBinding_operations Operations of Binding "RibbonIntelPaperWsServiceServiceSoapBinding"

  - @ref __ns1__ribbonPaperCheck

  - @ref __ns1__ribbonPaperIn

@section RibbonIntelPaperWsServiceServiceSoapBinding_ports Endpoints of Binding "RibbonIntelPaperWsServiceServiceSoapBinding"

  - http://192.168.216.158:8083/ribbonIntelWs

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   RibbonIntelPaperWsServiceServiceSoapBinding                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__ribbonPaperCheck                                                  *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__ribbonPaperCheck" of service binding "RibbonIntelPaperWsServiceServiceSoapBinding".

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__ribbonPaperCheck(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__ribbonPaperCheck*              ns1__ribbonPaperCheck_,
    // output parameters:
    ns1__ribbonPaperCheckResponse      &ns1__ribbonPaperCheckResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__ribbonPaperCheck(
    struct soap *soap,
    // input parameters:
    ns1__ribbonPaperCheck*              ns1__ribbonPaperCheck_,
    // output parameters:
    ns1__ribbonPaperCheckResponse      &ns1__ribbonPaperCheckResponse_
  );
@endcode

C++ proxy class (defined in soapRibbonIntelPaperWsServiceServiceSoapBindingProxy.h):
@code
  class RibbonIntelPaperWsServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapRibbonIntelPaperWsServiceServiceSoapBindingService.h):
@code
  class RibbonIntelPaperWsServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	ribbonPaperCheck SOAP
//gsoap ns1  service method-style:	ribbonPaperCheck document
//gsoap ns1  service method-encoding:	ribbonPaperCheck literal
//gsoap ns1  service method-action:	ribbonPaperCheck ""
//gsoap ns1  service method-output-action:	ribbonPaperCheck Response
int __ns1__ribbonPaperCheck(
    ns1__ribbonPaperCheck*              ns1__ribbonPaperCheck_,	///< Input parameter
    ns1__ribbonPaperCheckResponse      &ns1__ribbonPaperCheckResponse_	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__ribbonPaperIn                                                     *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__ribbonPaperIn" of service binding "RibbonIntelPaperWsServiceServiceSoapBinding".

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__ribbonPaperIn(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__ribbonPaperIn*                 ns1__ribbonPaperIn_,
    // output parameters:
    ns1__ribbonPaperInResponse         &ns1__ribbonPaperInResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__ribbonPaperIn(
    struct soap *soap,
    // input parameters:
    ns1__ribbonPaperIn*                 ns1__ribbonPaperIn_,
    // output parameters:
    ns1__ribbonPaperInResponse         &ns1__ribbonPaperInResponse_
  );
@endcode

C++ proxy class (defined in soapRibbonIntelPaperWsServiceServiceSoapBindingProxy.h):
@code
  class RibbonIntelPaperWsServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapRibbonIntelPaperWsServiceServiceSoapBindingService.h):
@code
  class RibbonIntelPaperWsServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	ribbonPaperIn SOAP
//gsoap ns1  service method-style:	ribbonPaperIn document
//gsoap ns1  service method-encoding:	ribbonPaperIn literal
//gsoap ns1  service method-action:	ribbonPaperIn ""
//gsoap ns1  service method-output-action:	ribbonPaperIn Response
int __ns1__ribbonPaperIn(
    ns1__ribbonPaperIn*                 ns1__ribbonPaperIn_,	///< Input parameter
    ns1__ribbonPaperInResponse         &ns1__ribbonPaperInResponse_	///< Output parameter
);

/**

@page RibbonIntelPaperWsServiceServiceSoapBinding Binding "RibbonIntelPaperWsServiceServiceSoapBinding"

@section RibbonIntelPaperWsServiceServiceSoapBinding_policy_enablers Policy Enablers of Binding "RibbonIntelPaperWsServiceServiceSoapBinding"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "com.azwave.service.RibbonIntelPaperWsService"

  - <ribbonPaperCheck> (use wsdl2h option -g to auto-generate)

  - <ribbonPaperCheckResponse> (use wsdl2h option -g to auto-generate)

  - <ribbonPaperIn> (use wsdl2h option -g to auto-generate)

  - <ribbonPaperInResponse> (use wsdl2h option -g to auto-generate)

@section ns2 Top-level root elements of schema "com.azurewave.domain.OperationResult"

*/

/* End of WebService.h */
